name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Dependencies
        run: deno install
      
      - name: Run tests
        run: deno task test

      - name: Build Package
        run: deno task build

      - name: Compress build
        run: deno task package

      - name: Archive compressed build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/build.tar
